# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/TaskList.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/TaskList.proto',
  package='TaskListPackage',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14proto/TaskList.proto\x12\x0fTaskListPackage\"\x07\n\x05\x45mpty\"7\n\x11\x43reateTaskMessage\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\" \n\x12TaskCreatedMessage\x12\n\n\x02id\x18\x01 \x01(\r\"P\n\x0bTaskMessage\x12\n\n\x02id\x18\x01 \x01(\r\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x11\n\tcompleted\x18\x04 \x01(\x08\">\n\x0fTaskListMessage\x12+\n\x05tasks\x18\x01 \x03(\x0b\x32\x1c.TaskListPackage.TaskMessage\"!\n\x13\x43ompleteTaskMessage\x12\n\n\x02id\x18\x01 \x01(\r2\xf6\x01\n\x08TaskList\x12U\n\nCreateTask\x12\".TaskListPackage.CreateTaskMessage\x1a#.TaskListPackage.TaskCreatedMessage\x12\x45\n\tListTasks\x12\x16.TaskListPackage.Empty\x1a .TaskListPackage.TaskListMessage\x12L\n\x0c\x43ompleteTask\x12$.TaskListPackage.CompleteTaskMessage\x1a\x16.TaskListPackage.Emptyb\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='TaskListPackage.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=48,
)


_CREATETASKMESSAGE = _descriptor.Descriptor(
  name='CreateTaskMessage',
  full_name='TaskListPackage.CreateTaskMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='TaskListPackage.CreateTaskMessage.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='TaskListPackage.CreateTaskMessage.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=105,
)


_TASKCREATEDMESSAGE = _descriptor.Descriptor(
  name='TaskCreatedMessage',
  full_name='TaskListPackage.TaskCreatedMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='TaskListPackage.TaskCreatedMessage.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=139,
)


_TASKMESSAGE = _descriptor.Descriptor(
  name='TaskMessage',
  full_name='TaskListPackage.TaskMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='TaskListPackage.TaskMessage.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='TaskListPackage.TaskMessage.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='TaskListPackage.TaskMessage.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='completed', full_name='TaskListPackage.TaskMessage.completed', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=221,
)


_TASKLISTMESSAGE = _descriptor.Descriptor(
  name='TaskListMessage',
  full_name='TaskListPackage.TaskListMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tasks', full_name='TaskListPackage.TaskListMessage.tasks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=285,
)


_COMPLETETASKMESSAGE = _descriptor.Descriptor(
  name='CompleteTaskMessage',
  full_name='TaskListPackage.CompleteTaskMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='TaskListPackage.CompleteTaskMessage.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=320,
)

_TASKLISTMESSAGE.fields_by_name['tasks'].message_type = _TASKMESSAGE
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['CreateTaskMessage'] = _CREATETASKMESSAGE
DESCRIPTOR.message_types_by_name['TaskCreatedMessage'] = _TASKCREATEDMESSAGE
DESCRIPTOR.message_types_by_name['TaskMessage'] = _TASKMESSAGE
DESCRIPTOR.message_types_by_name['TaskListMessage'] = _TASKLISTMESSAGE
DESCRIPTOR.message_types_by_name['CompleteTaskMessage'] = _COMPLETETASKMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'proto.TaskList_pb2'
  # @@protoc_insertion_point(class_scope:TaskListPackage.Empty)
  })
_sym_db.RegisterMessage(Empty)

CreateTaskMessage = _reflection.GeneratedProtocolMessageType('CreateTaskMessage', (_message.Message,), {
  'DESCRIPTOR' : _CREATETASKMESSAGE,
  '__module__' : 'proto.TaskList_pb2'
  # @@protoc_insertion_point(class_scope:TaskListPackage.CreateTaskMessage)
  })
_sym_db.RegisterMessage(CreateTaskMessage)

TaskCreatedMessage = _reflection.GeneratedProtocolMessageType('TaskCreatedMessage', (_message.Message,), {
  'DESCRIPTOR' : _TASKCREATEDMESSAGE,
  '__module__' : 'proto.TaskList_pb2'
  # @@protoc_insertion_point(class_scope:TaskListPackage.TaskCreatedMessage)
  })
_sym_db.RegisterMessage(TaskCreatedMessage)

TaskMessage = _reflection.GeneratedProtocolMessageType('TaskMessage', (_message.Message,), {
  'DESCRIPTOR' : _TASKMESSAGE,
  '__module__' : 'proto.TaskList_pb2'
  # @@protoc_insertion_point(class_scope:TaskListPackage.TaskMessage)
  })
_sym_db.RegisterMessage(TaskMessage)

TaskListMessage = _reflection.GeneratedProtocolMessageType('TaskListMessage', (_message.Message,), {
  'DESCRIPTOR' : _TASKLISTMESSAGE,
  '__module__' : 'proto.TaskList_pb2'
  # @@protoc_insertion_point(class_scope:TaskListPackage.TaskListMessage)
  })
_sym_db.RegisterMessage(TaskListMessage)

CompleteTaskMessage = _reflection.GeneratedProtocolMessageType('CompleteTaskMessage', (_message.Message,), {
  'DESCRIPTOR' : _COMPLETETASKMESSAGE,
  '__module__' : 'proto.TaskList_pb2'
  # @@protoc_insertion_point(class_scope:TaskListPackage.CompleteTaskMessage)
  })
_sym_db.RegisterMessage(CompleteTaskMessage)



_TASKLIST = _descriptor.ServiceDescriptor(
  name='TaskList',
  full_name='TaskListPackage.TaskList',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=323,
  serialized_end=569,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateTask',
    full_name='TaskListPackage.TaskList.CreateTask',
    index=0,
    containing_service=None,
    input_type=_CREATETASKMESSAGE,
    output_type=_TASKCREATEDMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ListTasks',
    full_name='TaskListPackage.TaskList.ListTasks',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_TASKLISTMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CompleteTask',
    full_name='TaskListPackage.TaskList.CompleteTask',
    index=2,
    containing_service=None,
    input_type=_COMPLETETASKMESSAGE,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TASKLIST)

DESCRIPTOR.services_by_name['TaskList'] = _TASKLIST

# @@protoc_insertion_point(module_scope)
