# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from server.proto import TaskList_pb2 as proto_dot_TaskList__pb2


class TaskListStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTask = channel.unary_unary(
                '/TaskListPackage.TaskList/CreateTask',
                request_serializer=proto_dot_TaskList__pb2.CreateTaskMessage.SerializeToString,
                response_deserializer=proto_dot_TaskList__pb2.TaskCreatedMessage.FromString,
                )
        self.ListTasks = channel.unary_unary(
                '/TaskListPackage.TaskList/ListTasks',
                request_serializer=proto_dot_TaskList__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_TaskList__pb2.TaskListMessage.FromString,
                )
        self.CompleteTask = channel.unary_unary(
                '/TaskListPackage.TaskList/CompleteTask',
                request_serializer=proto_dot_TaskList__pb2.CompleteTaskMessage.SerializeToString,
                response_deserializer=proto_dot_TaskList__pb2.Empty.FromString,
                )


class TaskListServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskListServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTask,
                    request_deserializer=proto_dot_TaskList__pb2.CreateTaskMessage.FromString,
                    response_serializer=proto_dot_TaskList__pb2.TaskCreatedMessage.SerializeToString,
            ),
            'ListTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTasks,
                    request_deserializer=proto_dot_TaskList__pb2.Empty.FromString,
                    response_serializer=proto_dot_TaskList__pb2.TaskListMessage.SerializeToString,
            ),
            'CompleteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteTask,
                    request_deserializer=proto_dot_TaskList__pb2.CompleteTaskMessage.FromString,
                    response_serializer=proto_dot_TaskList__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TaskListPackage.TaskList', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TaskList(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TaskListPackage.TaskList/CreateTask',
            proto_dot_TaskList__pb2.CreateTaskMessage.SerializeToString,
            proto_dot_TaskList__pb2.TaskCreatedMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TaskListPackage.TaskList/ListTasks',
            proto_dot_TaskList__pb2.Empty.SerializeToString,
            proto_dot_TaskList__pb2.TaskListMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CompleteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TaskListPackage.TaskList/CompleteTask',
            proto_dot_TaskList__pb2.CompleteTaskMessage.SerializeToString,
            proto_dot_TaskList__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
